{"name": "test_user_registration", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to have text 'Your Account Has Been Created!!'\nActual value: Your Account Has Been Created! \nCall log:\n  - Expect \"to_have_text\" with timeout 5000ms\n  - waiting for locator(\"h1:has-text(\\\"Your Account Has Been Created!\\\")\")\n    9 × locator resolved to <h1>Your Account Has Been Created!</h1>\n      - unexpected value \"Your Account Has Been Created!\"", "trace": "page = <Page url='https://tutorialsninja.com/demo/index.php?route=account/success'>\n\n    @pytest.mark.sanity\n    @pytest.mark.regression\n    def test_user_registration(page):\n        home_page=HomePage(page)\n        registration_page=RegistrationPage(page)\n    \n        home_page.click_my_account()\n        home_page.click_register()\n    \n        random_data=RandomDataUtil()\n    \n        first_name=random_data.get_first_name()\n        last_name = random_data.get_last_name()\n        email = random_data.get_email()\n        phone = random_data.get_phone_number()\n        password = random_data.get_password()\n    \n        registration_page.set_first_name(first_name)\n        registration_page.set_last_name(last_name)\n        registration_page.set_email(email)\n        registration_page.set_telephone(phone)\n        registration_page.set_password(password)\n        registration_page.set_confirm_password(password)\n    \n        registration_page.set_privacy_policy()\n        registration_page.click_continue()\n    \n        confirmation_msg=registration_page.get_confirmation_msg()\n>       expect(confirmation_msg).to_have_text(\"Your Account Has Been Created!!\")\nE       AssertionError: Locator expected to have text 'Your Account Has Been Created!!'\nE       Actual value: Your Account Has Been Created! \nE       Call log:\nE         - Expect \"to_have_text\" with timeout 5000ms\nE         - waiting for locator(\"h1:has-text(\\\"Your Account Has Been Created!\\\")\")\nE           9 × locator resolved to <h1>Your Account Has Been Created!</h1>\nE             - unexpected value \"Your Account Has Been Created!\"\n\ntests\\test_user_registration.py:61: AssertionError"}, "attachments": [{"name": "stdout", "source": "e5d4b8b2-1a7a-42dc-8de4-8ddcaa5db1db-attachment.txt", "type": "text/plain"}], "start": 1761579484845, "stop": 1761579491635, "uuid": "3ae6d5cc-7154-49f7-8e25-b988097f3188", "historyId": "541394ea0cfde4c8462c2d79980c4244", "testCaseId": "541394ea0cfde4c8462c2d79980c4244", "fullName": "tests.test_user_registration#test_user_registration", "labels": [{"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_registration"}, {"name": "host", "value": "Pavan-Lenova"}, {"name": "thread", "value": "6136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_registration"}], "titlePath": ["tests", "test_user_registration.py"]}